### ISSUE TITLE
Not all pos_proportions output

### ISSUE THREAD

**Issue by toltoxgh** [HLasse/TextDescriptives#288] opened 2023-10-27 21:35 UTC
## How to reproduce the behaviour

I noticed another example of the 'pos_proportions' metric not extracting all pos tags, similarly as discussed in https://github.com/HLasse/TextDescriptives/discussions/221

A demo code is below, as can be seen in the output, the tag 'pos_prop_SPACE' is only outputted to the result df with the larger text input. Should the user set the argument somewhere to always output all pos tags, even if some are not found, or is it a bug?

    import textdescriptives as td

    from textdescriptives.utils import load_sms_data
    df_all = load_sms_data()

    for df in [df_all.head(200), df_all.head(5)]:
        # assumes you have downloaded the ´en_core_web_model´
        metrics = td.extract_metrics(
            text=df["message"],
            spacy_model="en_core_web_sm",
            metrics=["pos_proportions"],
        )
        
        # join the metrics to the original dataframe to get the label
        metrics_df = df.join(metrics.drop(columns=["text"]))
        columns_metrics = metrics_df.columns
        print(len(columns_metrics))
        print(columns_metrics)

## Your Environment

* textdescriptives Version Used: 2.7.0
* Operating System:
* Python Version Used: 3.9

**Comment by KennethEnevoldsen** [comment] 2023-10-30 07:33
It is not a bug. Proportions are only calculated using the POS which are present. 

Therefore, it will only be added if the POS tag appears in at least one of the texts. 

I agree it would be ideal to have the dataframe be of a consistent size this would however prevent custom POS tags. Potentially it could also be extracted from the pipeline (then it would be consistent pr. Pipeline)

@HLasse what are your thoughts?

**Comment by HLasse** [comment] 2023-10-31 10:44
This should actually have been fixed in #222 - I'll have a look

**Comment by HLasse** [comment] 2023-10-31 14:14
Thanks for reporting the bug @toltoxgh - this should now be fixed in #290

**Closed** 2023-10-31 14:48 UTC
Labels: enhancement
